### ISSUE TITLE
Validator: Invalid

### ISSUE THREAD

**Issue by fynman** [LeFnord/grape-swagger#4] opened 2015-12-19 21:02 UTC
Hi LeFnord,

  I've tried to use your fork to implement a swagger 2 specification. At the moment, the swagger validator evaluates to Invalid.

  Any idea what might be going on? 

  My swagger (ui) is hosted on: http://e27.cloudapp.net:9292/swagger-ui

Thanks!
Bart

**Comment by pswenson** [comment] 2015-12-20 00:03
I tried hitting it, no go.  is the url correct?  thanks

**Comment by fynman** [comment] 2015-12-20 13:23
Hi Phil,

  It must have been very late ;-)

  http://e27.cloudapp.net:9292/swagger-ui

Thanks,

Bart

**Comment by LeFnord** [comment] 2015-12-21 08:19
mmh, sorry, could not access your swagger-ui, to see what's happen :(

**Comment by fynman** [comment] 2015-12-21 08:42
Did you try http://e27.cloudapp.net:9292/swagger-ui ? Works here

**Comment by LeFnord** [comment] 2015-12-21 09:12
yeap, now I can access it (but only with my phone, I'm at work and the access is restricted, so I will take a deeper look today evening, germany time), but I can see a general problem of the translation from grape to swagger … it would be expected to declare the counts of elements of an array/collection, means `oneOf`, `anyOf`, etc. but this is an information this is not present on the grape side, cause it is simple not needed, because you are describing always an array, independent if your are exposing all elements or an subset of of.

This is a point there I need input and help to specify the behavior, cause it differs in many points from spec 1.2.

I had a similar failing validation (it was `allOf`), but the swagger.json could be used to import into AWS and Azure.

**Comment by fynman** [comment] 2015-12-28 23:52
did you get support to solve this?

thanks,
Bart

**Comment by LeFnord** [comment] 2016-01-04 19:17
not really, the problem is, there one could not be find a specification in the swagger spec, so I can only solve it by try&error, but at the moment there is no time, and – as I mentioned above – it works with the validation errors ;)

**Comment by fynman** [comment] 2016-01-04 19:45
Thanks for the feedback

Where in the source should I start if I want to solve the validation error?

**Comment by LeFnord** [comment] 2016-01-05 08:56
Hi fynman,

I think the [`method_object`](https://github.com/LeFnord/grape-swagger/blob/master/lib/grape-swagger/endpoint.rb#L126) method is a good starting point, this is responsible for all stuff, which one could find under:

```
"paths"=>{
  "/path"=>{
    "get|post|…"=>
```

**Comment by LeFnord** [comment] 2016-03-24 14:00
think I found the failure, some parameter properties have change/are removed,
these changes would be merged soon, …
please, use for further work, issues and PRs the official repo for swagger-2.0, which could be found here
https://github.com/ruby-grape/grape-swagger/tree/swagger-2.0

**Closed as completed by LeFnord** 2016-03-24 14:00 UTC
